[package]
name = "ruuvi"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluez-async = "0.6"
futures = "0.3"
chrono = "0.4"
chrono-tz = "0.8"
tokio = { version = "1.14", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11" }
